---
abstract: 'We are the Indian CPAN Authors. Coming from that big peninsula in the center of Asia, the original Indians. The ones columbus was looking for. :)'
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-India
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Acme::CPANAuthors::India:
    file: lib/Acme/CPANAuthors/India.pm
    version: 0.07
requires:
  Acme::CPANAuthors::Register: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/shantanubhadoria/acme-cpanauthors-india/issues
  homepage: https://metacpan.org/release/Acme-CPANAuthors-India
  repository: git://github.com/shantanubhadoria/acme-cpanauthors-india.git
version: 0.07
x_contributors:
  - 'Shantanu <shantanu@cpan.org>'
  - 'Shantanu Bhadoria <shantanu.bhadoria@gmail.com>'
